<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>artemis_mission_manager</name>
  <version>0.1.0</version>
  <description>Mission-level orchestration</description>
  <maintainer email="jasmeet0915@gmail.com">Jasmeet Singh</maintainer>
  <license>Apache-2.0</license>
  <author email="jasmeet0915@gmail.com">Jasmeet Singh</author>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>rclcpp</depend>
  <depend>ament_index_cpp</depend>
  <depend>artemis_mission_interfaces</depend>
  <depend>yaml-cpp</depend>

  <test_depend>ament_cmake_gtest</test_depend>
  <test_depend>launch_testing_ament_cmake</test_depend>
  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_lint_common</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
